# Generated by Django 4.1 on 2022-09-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='skippable',
            field=models.BooleanField(default=True),
        ),
    ]
